In [1]:
import os
import librosa
import numpy as np
import torch
from torch.utils.data import DataLoader
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu


In [4]:
sample_audio_file_path = "/content/drive/MyDrive/CSCI_534/534_project/Edited"


In [5]:
sample_audio_file_path

'/content/drive/MyDrive/CSCI_534/534_project/Edited'

In [6]:
import os

def list_all_files(folder_path):
    # Walk through all directories and files in folder_path
    for dirpath, dirnames, filenames in os.walk(folder_path):
        for filename in filenames:
            # Print full path of each file
            print(os.path.join(dirpath, filename))

# Specify the folder path
folder_path = sample_audio_file_path
list_all_files(folder_path)


/content/drive/MyDrive/CSCI_534/534_project/Edited/CustServ1.mp3
/content/drive/MyDrive/CSCI_534/534_project/Edited/CustServ7.mp3
/content/drive/MyDrive/CSCI_534/534_project/Edited/CustServ8.mp3
/content/drive/MyDrive/CSCI_534/534_project/Edited/CustServ9.mp3
/content/drive/MyDrive/CSCI_534/534_project/Edited/CustServ10.mp3
/content/drive/MyDrive/CSCI_534/534_project/Edited/CustServ11.mp3
/content/drive/MyDrive/CSCI_534/534_project/Edited/CustServ12.mp3
/content/drive/MyDrive/CSCI_534/534_project/Edited/CustServ13.mp3
/content/drive/MyDrive/CSCI_534/534_project/Edited/CustServ14.mp3
/content/drive/MyDrive/CSCI_534/534_project/Edited/CustServ15.mp3
/content/drive/MyDrive/CSCI_534/534_project/Edited/CustServ16.mp3
/content/drive/MyDrive/CSCI_534/534_project/Edited/CustServ17.mp3
/content/drive/MyDrive/CSCI_534/534_project/Edited/CustServ18.mp3
/content/drive/MyDrive/CSCI_534/534_project/Edited/CustServ19.mp3
/content/drive/MyDrive/CSCI_534/534_project/Edited/CustServ20.mp3
/content/drive

In [7]:
pip install moviepy


In [8]:
import os
from moviepy.editor import *

def convert_mp3_to_wav(folder_path):
    # Define the output folder path
    output_folder = os.path.join(folder_path, 'Standard')

    # Create the output folder if it doesn't already exist
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)

    # Loop through all the files in the folder
    for filename in os.listdir(folder_path):
        if filename.endswith(".mp3"):
            # Construct the full file path
            full_path = os.path.join(folder_path, filename)
            # Load the audio file
            audio = AudioFileClip(full_path)
            # Construct the output filename
            wav_filename = os.path.splitext(filename)[0] + ".wav"
            wav_file_path = os.path.join(output_folder, wav_filename)
            # Write the audio to a WAV file
            audio.write_audiofile(wav_file_path)
            # Close the audio file to release resources
            audio.close()

# Specify the folder containing the MP3 files
folder_path = sample_audio_file_path
convert_mp3_to_wav(folder_path)


MoviePy - Writing audio in /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ1.wav


MoviePy - Done.
MoviePy - Writing audio in /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ7.wav


MoviePy - Done.
MoviePy - Writing audio in /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ8.wav


MoviePy - Done.
MoviePy - Writing audio in /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ9.wav


MoviePy - Done.
MoviePy - Writing audio in /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ10.wav


MoviePy - Done.
MoviePy - Writing audio in /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ11.wav


MoviePy - Done.
MoviePy - Writing audio in /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ12.wav


MoviePy - Done.
MoviePy - Writing audio in /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ13.wav


MoviePy - Done.
MoviePy - Writing audio in /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ14.wav


MoviePy - Done.
MoviePy - Writing audio in /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ15.wav


MoviePy - Done.
MoviePy - Writing audio in /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ16.wav


MoviePy - Done.
MoviePy - Writing audio in /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ17.wav


MoviePy - Done.
MoviePy - Writing audio in /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ18.wav


MoviePy - Done.
MoviePy - Writing audio in /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ19.wav


MoviePy - Done.
MoviePy - Writing audio in /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ20.wav


MoviePy - Done.
MoviePy - Writing audio in /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ21.wav


MoviePy - Done.
MoviePy - Writing audio in /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ22.wav


MoviePy - Done.
MoviePy - Writing audio in /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ23.wav


MoviePy - Done.
MoviePy - Writing audio in /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ2.wav


MoviePy - Done.
MoviePy - Writing audio in /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ3.wav


MoviePy - Done.
MoviePy - Writing audio in /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ4.wav


MoviePy - Done.
MoviePy - Writing audio in /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ5.wav


MoviePy - Done.
MoviePy - Writing audio in /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ6.wav


MoviePy - Done.


In [9]:
!pip install resampy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 10.3 MB/s eta 0:00:00


In [10]:
def load_audio(file_path, target_sr=16000):
    # Load the file with librosa, which automatically resamples to the target_sr
    audio, sample_rate = librosa.load(file_path, res_type='kaiser_fast',duration=2.5,sr=22050*2,offset=0.5)
    return audio,sample_rate



In [11]:
import torch.nn as nn
class multiple_class_model(torch.nn.Module):
    def __init__(self,input_size,emo_size=8,hidden_size=256,hidden_size2=128,hidden_size3 = 64,drop_out=0.2, denseN=10,norm_type="Batch"):
        super(multiple_class_model, self).__init__()
        self.input_size = input_size #X_train.shape[1]
        self.emo_size = emo_size
        self.hidden1 = hidden_size
        self.hidden2 = hidden_size2
        self.drop_out = drop_out
        self.dense = denseN
        if norm_type == "Batch":
            self.Norm1 = nn.BatchNorm1d(hidden_size)
            self.Norm2 = nn.BatchNorm1d(hidden_size3)
        elif norm_type == "Layer":
            self.Norm1 = nn.LayerNorm(hidden_size)
            self.Norm2 = nn.LayerNorm(hidden_size3)
        self.Conv1 = nn.Conv1d(in_channels=1,
                                out_channels=hidden_size,
                                kernel_size=5,
                                padding='same')
        self.maxP = nn.MaxPool1d(kernel_size=8, stride=8, padding=0)

        self.Conv2 = nn.Conv1d(in_channels=hidden_size,
                                out_channels=hidden_size2,
                                kernel_size=5,
                                padding='same')

        self.Conv3 = nn.Conv1d(in_channels=hidden_size2,
                                out_channels=hidden_size3,
                                kernel_size=5,
                                padding='same')
        # self.whole_model = nn.Sequential(
        #     nn.Conv1d(in_channels=input_size,
        #                         out_channels=hidden_size,
        #                         kernel_size=5,
        #                         padding='same'),
        #     self.Norm1,
        #     nn.ReLU(),
        #     nn.Conv1d(in_channels=hidden_size,
        #                         out_channels=hidden_size2,
        #                         kernel_size=5,
        #                         padding='same'),
        #     nn.ReLU(),
        #     nn.Dropout(p=drop_out),
        #     nn.MaxPool1d(kernel_size=8, stride=8, padding=0),
        #     nn.Conv1d(in_channels=hidden_size2,
        #                         out_channels=hidden_size3,
        #                         kernel_size=5,
        #                         padding='same'),
        #     self.Norm2,
        #     nn.ReLU(),
        #     nn.Flatten()
        # )
        self.gender_linear = nn.Linear(hidden_size3 * (input_size//8),2)
        self.emo_linear = nn.Linear(hidden_size3 * (input_size//8),emo_size)

    def forward(self,x):
        # print(type(x))
        x = torch.tensor(x)
        x = x.to(device)
        #print(x.shape)
        x = x.unsqueeze(1)
        x = self.Conv1(x)
        x = self.Norm1(x)
        x = nn.ReLU()(x)
        x = self.Conv2(x)
        x = nn.Dropout(p=self.drop_out)(x)
        x = self.maxP(x)
        x = self.Conv3(x)
        x = self.Norm2(x)
        x = nn.ReLU()(x)
        x = nn.Flatten()(x)
        gender = self.gender_linear(x)
        emo = self.emo_linear(x)
        final_layer = nn.Softmax(dim=1)
        gender = final_layer(gender)
        emo = final_layer(emo)
        #print(gender)
        #print(emo)
        return emo,gender

In [12]:
import tensorflow_hub as hub
def init():
  yamnet_model_handle = 'https://tfhub.dev/google/yamnet/1'
  pre_model = hub.load(yamnet_model_handle)
  input_n = 1024
  model = multiple_class_model(input_n)
  model.load_state_dict(torch.load("/content/drive/MyDrive/CSCI_534/534_project/best_model.pth", map_location=torch.device('cpu')))
  return pre_model, model

In [13]:
def predict(path):
  waveform, sr = load_audio(path)
  scores, embeddings, spectrogram = pre_model(waveform)
  # print(embeddings)
  features = np.mean(embeddings, axis=0)
  features = features.reshape((1, 1024))
  # print(embeddings.shape)
  # print(features.shape)
  emo, gender = model.forward(features)
  print(emo)
  print(gender)
  return emo, gender

In [14]:
pre_model, model = init()


In [15]:
directory_path = "/content/drive/MyDrive/CSCI_534/534_project/Edited/Standard"


In [16]:
audio_files = [os.path.join(directory_path, f) for f in os.listdir(directory_path) if f.endswith('.wav')]
audio_files

['/content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ7.wav',
 '/content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ1.wav',
 '/content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ8.wav',
 '/content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ9.wav',
 '/content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ10.wav',
 '/content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ11.wav',
 '/content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ12.wav',
 '/content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ13.wav',
 '/content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ14.wav',
 '/content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ15.wav',
 '/content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ16.wav',
 '/content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ17.wav',
 '/content/drive/MyDrive/CSCI_534/534_project/Edited/Sta

In [17]:
emotions = []
genders = []

In [18]:
for file_path in audio_files:
    print("Processing:", file_path)
    try:
        emo, gender = predict(file_path)
        # Make sure to detach from the graph and convert to numpy
        emotions.append(emo.detach().cpu().numpy())
        genders.append(gender.detach().cpu().numpy())
    except Exception as e:
        print(f"Error processing {file_path}: {str(e)}")


Processing: /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ7.wav
tensor([[0.1382, 0.0678, 0.0567, 0.3527, 0.1978, 0.0645, 0.0614, 0.0608]],
       grad_fn=<SoftmaxBackward0>)
tensor([[0.4975, 0.5025]], grad_fn=<SoftmaxBackward0>)
Processing: /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ1.wav
tensor([[0.1561, 0.0603, 0.0494, 0.3363, 0.2304, 0.0645, 0.0506, 0.0524]],
       grad_fn=<SoftmaxBackward0>)
tensor([[0.4817, 0.5183]], grad_fn=<SoftmaxBackward0>)
Processing: /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ8.wav
tensor([[0.1506, 0.0706, 0.0575, 0.3442, 0.1952, 0.0670, 0.0575, 0.0575]],
       grad_fn=<SoftmaxBackward0>)
tensor([[0.4879, 0.5121]], grad_fn=<SoftmaxBackward0>)
Processing: /content/drive/MyDrive/CSCI_534/534_project/Edited/Standard/CustServ9.wav
tensor([[0.1433, 0.0643, 0.0616, 0.3504, 0.1977, 0.0639, 0.0591, 0.0597]],
       grad_fn=<SoftmaxBackward0>)
tensor([[0.4952, 0.5048]], grad_fn=<SoftmaxBackward

In [19]:
mean_emotion = np.mean(emotions, axis=0)


In [20]:
mean_emotion

array([[0.1531899 , 0.05571735, 0.04910028, 0.3390017 , 0.24351877,
        0.05906275, 0.05122824, 0.04918102]], dtype=float32)

In [21]:
print("Mean Emotion:", mean_emotion)
print("Emotions Shape:", emotions.shape)
print("Sample Gender Predictions:", genders[:5])  # Display first 5 gender predictions as an example
print("Genders Shape:", genders.shape)

Mean Emotion: [[0.1531899  0.05571735 0.04910028 0.3390017  0.24351877 0.05906275
  0.05122824 0.04918102]]


AttributeError: 'list' object has no attribute 'shape'

In [105]:
fp = "/content/drive/MyDrive/CSCI_534/534_project/534 script2 gao.wav"

In [106]:
fp

'/content/drive/MyDrive/CSCI_534/534_project/534 script2 gao.wav'

In [107]:
emo, gender = predict(fp)
print(emo)
print(emo.shape)
print(gender)
print(gender.shape)

tensor([[0.1535, 0.0518, 0.0380, 0.3138, 0.3057, 0.0531, 0.0412, 0.0428]],
       grad_fn=<SoftmaxBackward0>)
tensor([[0.4874, 0.5126]], grad_fn=<SoftmaxBackward0>)
tensor([[0.1535, 0.0518, 0.0380, 0.3138, 0.3057, 0.0531, 0.0412, 0.0428]],
       grad_fn=<SoftmaxBackward0>)
torch.Size([1, 8])
tensor([[0.4874, 0.5126]], grad_fn=<SoftmaxBackward0>)
torch.Size([1, 2])


In [108]:
# prompt: make emo into list with 6 decimal

emo_list = list(map(lambda x: round(x, 6), emo[0].tolist()))


In [109]:
emo_list

[0.153497,
 0.051831,
 0.038007,
 0.313821,
 0.305666,
 0.053123,
 0.041232,
 0.042823]